gui:
  border: "rounded"
  theme:
    inactiveBorderColor:
      - "#9b9ea4"
confirmOnQuit: false
promptToReturnFromSubprocess: false

os:
  edit: "nvim -c 'DiffviewOpen' {{filename}}"
  editAtLine: "nvim -c 'DiffviewOpen' {{filename}}"

# git:
#   paging:
#     colorArg: always
#     pager: delta --paging=never
