gui:
  border: 'rounded'
  theme:
    inactiveBorderColor:
      #- "#4C566A" # nordic
      # - "#3b4261"
      - "#9b9ea4"
git:
  paging:
    externalDiffCommand: difft --color=always --syntax-highlight=on --display=inline
