require 'alex.ui.tree'
require 'alex.ui.git'
require 'alex.ui.lualine'
require 'alex.ui.components'
require 'alex.ui.terminal'
-- require 'alex.ui.bufferline'
require 'alex.ui.barbar'
require 'alex.ui.dashboard'
require 'alex.ui.telescope'
