FROM ubuntu:25.10

# OS Stuff.
RUN apt-get update && apt-get install -y \
    curl wget python3 python3-pip \
    software-properties-common sudo neovim \
    # Kernel source.
    linux-source linux-headers-generic \
    # Kernel deps.
    flex bison bc debhelper rsync kmod cpio libelf-dev:native libssl-dev:native libdw-dev:native

WORKDIR /root

# Set default command
CMD ["/bin/bash"]
