FROM debian:12

# Update package list and install essential packages
RUN apt-get update && apt-get install -y \
    # General
    curl wget python3 python3-pip software-properties-common neovim sudo \
    # Kernel source
    linux-source-6.1 linux-headers-6.1.0-42-common \
    # Kernel deps
    pahole


WORKDIR /root

# Set default command
CMD ["/bin/bash"]
